### ISSUE TITLE
6.0.0rc2 crashes with -Wp,-D_GLIBCXX_ASSERTIONS

### ISSUE THREAD

**Issue by QuLogic** [OSGeo/PROJ#1290]
Fedora builds with various hardening checks enabled, one of which is `_GLIBCXX_ASSERTIONS`, which does this according to the docs:
> When defined, enables extra error checking in the form of precondition assertions, such as bounds checking in strings and null pointer checks when dereferencing smart pointers.

This causes a crash in the tests, due to a null pointer:
```
$ export CFLAGS=-g CXXFLAGS='-g -Wp,-D_GLIBCXX_ASSERTIONS'
$ ./autogen.sh && ./configure && make -j8
# Replicate the first part of cli tests:
$ PROJ_LIB=./data LD_LIBRARY_PATH=./src/.libs/ gdb --args ./src/.libs/projinfo -s NAD27 -t NAD83 --grid-check none --spatial-test intersects
(gdb) r
Starting program: ./src/.libs/projinfo -s NAD27 -t NAD83 --grid-check none --spatial-test intersects
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Candidate operations found: 7
-------------------------------------
Operation n°1:

DERIVED_FROM(EPSG):1312, NAD27 to NAD83 (3), 1.0 m, Canada, at least one grid missing

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=hgridshift +grids=ntv1_can.dat +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1

WKT2_2018 string:
/usr/include/c++/8/bits/unique_ptr.h:328: typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp, _Dp>::operator*() const [with _Tp = osgeo::proj::common::Measure; _Dp = std::default_delete<osgeo::proj::common::Measure>; typename std::add_lvalue_reference<_Tp>::type = osgeo::proj::common::Measure&]: Assertion 'get() != pointer()' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff74e353f in raise () from /lib64/libc.so.6

(gdb) bt
#0  0x00007ffff74e353f in raise () from /lib64/libc.so.6
#1  0x00007ffff74cd895 in abort () from /lib64/libc.so.6
#2  0x00007ffff7cb87e3 in std::__replacement_assert (__file=0x7ffff7ebc078 "/usr/include/c++/8/bits/unique_ptr.h", __line=328, 
    __function=0x7ffff7ebe780 <std::unique_ptr<osgeo::proj::common::Measure, std::default_delete<osgeo::proj::common::Measure> >::operator*() const::__PRETTY_FUNCTION__> "typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp, _Dp>::operator*() const [with _Tp = osgeo::proj::common::Measure; _Dp = std::default_delete<osgeo::proj::common::Measure>; typename s"..., __condition=0x7ffff7ebc065 "get() != pointer()")
    at /usr/include/c++/8/x86_64-redhat-linux/bits/c++config.h:2391
#3  0x00007ffff7d710bd in std::unique_ptr<osgeo::proj::common::Measure, std::default_delete<osgeo::proj::common::Measure> >::operator* (
    this=0x511bd8) at /usr/include/c++/8/bits/unique_ptr.h:328
#4  0x00007ffff7d3afc8 in osgeo::proj::operation::ParameterValue::value (this=0x509190) at iso19111/coordinateoperation.cpp:2117
#5  0x00007ffff7d3b0b8 in osgeo::proj::operation::ParameterValue::_exportToWKT (this=0x509190, formatter=0x510b50)
    at iso19111/coordinateoperation.cpp:2159
#6  0x00007ffff7d36e20 in osgeo::proj::operation::OperationParameterValue::_exportToWKT (this=0x705490, formatter=0x510b50, mapping=0x0)
    at iso19111/coordinateoperation.cpp:1090
#7  0x00007ffff7d50a4e in osgeo::proj::operation::SingleOperation::exportTransformationToWKT (this=0x4f8130, formatter=0x510b50)
    at iso19111/coordinateoperation.cpp:7666
#8  0x00007ffff7d506d3 in osgeo::proj::operation::Transformation::_exportToWKT (this=0x4f8130, formatter=0x510b50)
    at iso19111/coordinateoperation.cpp:7622
#9  0x00007ffff7d92660 in osgeo::proj::io::IWKTExportable::exportToWKT[abi:cxx11](osgeo::proj::io::WKTFormatter*) const (this=0x4f8160, 
    formatter=0x510b50) at iso19111/io.cpp:108
#10 0x0000000000417663 in outputObject (dbContext=std::shared_ptr<osgeo::proj::io::DatabaseContext> (use count 3, weak count 0) = {...}, obj=..., 
    allowUseIntermediateCRS=osgeo::proj::operation::CoordinateOperationContext::IntermediateCRSUse::IF_NO_DIRECT_TRANSFORMATION, outputOpt=...)
    at apps/projinfo.cpp:366
#11 0x000000000041966b in outputOperations (dbContext=std::shared_ptr<osgeo::proj::io::DatabaseContext> (use count 3, weak count 0) = {...}, 
    sourceCRSStr="NAD27", targetCRSStr="NAD83", bboxFilter=std::shared_ptr<osgeo::proj::metadata::Extent> (empty) = {...}, 
    spatialCriterion=osgeo::proj::operation::CoordinateOperationContext::SpatialCriterion::PARTIAL_INTERSECTION, 
    spatialCriterionExplicitlySpecified=true, crsExtentUse=osgeo::proj::operation::CoordinateOperationContext::SourceTargetCRSExtentUse::SMALLEST, 
    gridAvailabilityUse=osgeo::proj::operation::CoordinateOperationContext::GridAvailabilityUse::IGNORE_GRID_AVAILABILITY, 
    allowUseIntermediateCRS=osgeo::proj::operation::CoordinateOperationContext::IntermediateCRSUse::IF_NO_DIRECT_TRANSFORMATION, 
    pivots=std::vector of length 0, capacity 0, authority="", usePROJGridAlternatives=true, showSuperseded=false, outputOpt=..., summary=false)
    at apps/projinfo.cpp:661
#12 0x000000000041c3b5 in main (argc=9, argv=0x7fffffffce78) at apps/projinfo.cpp:1128
```

**Comment by QuLogic** [comment]
Bisect goes back to the mega-commit of #1040, so I guess from its initial writeup.

**Comment by QuLogic** [comment]
Bisect on the PR seems to point to e709461583523670c824322b6d03c537e717a825, but it's a pretty big commit itself.

**Comment by rouault** [comment]
@QuLogic I've the fix ready. No need to further bisect on your side

**Comment by QuLogic** [comment]
Ah great; I was going to stop there anyway.
