### ISSUE TITLE
Support for creating/exporting Ellipsoid, PrimeMeridian, Datum using PROJ strings

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1548]
Are there plans for adding support for creating/exporting a Datum, Ellipsoid, PrimeMeridian, etc. Using PROJ strings via the `proj_create` C-API?

Currently it all works using WKT strings and I can also create them using `proj_create_from_database` using an EPSG code. But, I am curious about the thoughts on supporting PROJ strings as well?

```python
>>> from pyproj.crs import CRS, Ellipsoid, Datum, PrimeMeridian
>>> cc = CRS("epsg:3857")
>>> cc.datum
DATUM["World Geodetic System 1984",
    ELLIPSOID["WGS 84",6378137,298.257223563,
        LENGTHUNIT["metre",1]],
    ID["EPSG",6326]]
>>> cc.datum.to_proj4()
>>> datum = Datum.from_string("+datum=WGS84")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyproj/_crs.pyx", line 826, in pyproj._crs.Datum.from_string
    raise CRSError(
pyproj.exceptions.CRSError: Invalid datum string: +datum=WGS84: (Internal Proj Error: proj_create: unrecognized format / unknown name)
>>> cc.ellipsoid.to_proj4()
'+ellps=WGS84'
>>> ellps = Ellipsoid.from_string("+ellps=WGS84")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyproj/_crs.pyx", line 571, in pyproj._crs.Ellipsoid.from_string
    raise CRSError(
pyproj.exceptions.CRSError: Invalid ellipsoid string: +ellps=WGS84: (Internal Proj Error: proj_create: unrecognized format / unknown name)
>>> cc.prime_meridian
PRIMEM["Greenwich",0,
    ANGLEUNIT["degree",0.0174532925199433],
    ID["EPSG",8901]]
>>> cc.prime_meridian.to_proj4()
'+proj=noop'
>>> pm = PrimeMeridian.from_string("+pm=greenwich")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyproj/_crs.pyx", line 721, in pyproj._crs.PrimeMeridian.from_string
    raise CRSError(
pyproj.exceptions.CRSError: Invalid prime meridian string: +pm=greenwich: (Internal Proj Error: proj_create: unrecognized format / unknown name)
>>> cc = CRS("+proj=latlon +pm=lisbon +datum=NAD83")
>>> cc
<Geographic 2D CRS: +proj=latlon +pm=lisbon +datum=NAD83 +type=crs>
Name: unknown
Axis Info [ellipsoidal]:
- lon[east]: Longitude (degree)
- lat[north]: Latitude (degree)
Area of Use:
- undefined
Datum: Unknown based on GRS 1980 ellipsoid
- Ellipsoid: GRS 1980
- Prime Meridian: Lisbon
>>> cc.datum
DATUM["Unknown based on GRS 1980 ellipsoid",
    ELLIPSOID["GRS 1980",6378137,298.257222101,
        LENGTHUNIT["metre",1],
        ID["EPSG",7019]]]
>>> cc.ellipsoid
ELLIPSOID["GRS 1980",6378137,298.257222101,
    LENGTHUNIT["metre",1],
    ID["EPSG",7019]]
```

**Comment by rouault** [comment]
> Are there plans for adding support for creating/exporting a Datum, Ellipsoid, PrimeMeridian, etc. Using PROJ strings via the `proj_create` C-API?

I'm -1 on this.  I want to "kill" PROJ strings for anything else than coodinate transformations

**Comment by snowman2** [comment]
> I want to "kill" PROJ strings for anything else than coodinate transformations

That is good to know. In that case I will plan accordingly. Thanks!
