### ISSUE TITLE
proj_create:crs not found for Java with ESRI wkid

### ISSUE THREAD

**Issue by davidraleigh** [OSGeo/PROJ#1704]
I have built Proj with JNI. EPSG projections are working with Java+JNI. But if I try to use an esri wkid projection with JNI I get an error `java.lang.IllegalArgumentException: +init=esri:54016`.

I build PROJ with the following specifications in order to use Java+JNI:
```bash
export PROJ_DIR=/usr/local/Cellar/proj/6.2.0
export JAVA_HOME="$(/usr/libexec/java_home)"
autoreconf -i
CFLAGS=-I$JAVA_HOME/include/darwin ./configure --with-jni=$JAVA_HOME/include --prefix=$PROJ_DIR
make -j 8
make install
cd jniwrap
ant -v
cp ./out/proj.jar $PROJ_DIR/lib/proj.jar
brew unlink proj && brew link proj
```

when I run this test with an esri projection defined with "+init=esri:54016".
```java
    @Test
    public void testProj6() throws Exception {
        PJ sourcePJ = new PJ("+init=epsg:4326");
        PJ targetPJ = new PJ("+init=esri:54016");

        double[] coordinates_WGS84 = {
                0, 0,   // First coordinate
                1, 1,   // Second coordinate
                2, -2    // Third coordinate
        };

        double[] coordinates_54016 = Arrays.copyOf(coordinates_WGS84, coordinates_WGS84.length);
        sourcePJ.transform(targetPJ, 2, coordinates_54016, 0, 3);

        double[] coordinates_4326 = Arrays.copyOf(coordinates_54016, coordinates_54016.length);
        targetPJ.transform(sourcePJ, 2, coordinates_4326, 0, 3);

        for (int i = 0; i < coordinates_WGS84.length; i++) {
            if (i == 1)
                continue;

            assertTrue((Math.abs(coordinates_WGS84[i] - coordinates_4326[i])) > 1);
            assertTrue((Math.abs(coordinates_4326[i] - coordinates_WGS84[i])) > 1);
            assertEquals(coordinates_4326[i], coordinates_WGS84[i]);
        }
    }
```

I get an error `java.lang.IllegalArgumentException: +init=esri:54016`
```bash
10 warnings
> Task :processTestResources UP-TO-DATE
> Task :testClasses
> Task :test FAILED

+init=esri:54016
java.lang.IllegalArgumentException: +init=esri:54016
	at org.proj4.PJ.<init>(Unknown Source)
	at com.esri.core.geometry.TestProjection.testProj6(TestProjection.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)

com.esri.core.geometry.TestProjection > testProj6 FAILED
    java.lang.IllegalArgumentException: +init=esri:54016
        at org.proj4.PJ.<init>(Unknown Source)
        at com.esri.core.geometry.TestProjection.testProj6(TestProjection.java:38)
```

The call:
`/usr/local/Cellar/proj/6.2.0/bin/projinfo esri:54016` executes as expected.

**Comment by rouault** [comment]
The existing Java bindings use the old PROJ API and are consequently not super up-to-date, and will probably be removed in a future PROJ version.
epsg:XXXX syntax has been kept in a compatibility mode when accessed from the old API, but not esri:XXXX.
Consider giving a try at https://github.com/Kortforsyningen/PROJ-JNI which will be the next Java bindings. Cf https://lists.osgeo.org/pipermail/proj/2019-October/008936.html
Or as a workaround use the 'esri' file from previous PROJ versions

**Comment by kbevers** [comment]
> Consider giving a try at Kortforsyningen/PROJ-JNI which will be the next Java bindings. Cf lists.osgeo.org/pipermail/proj/2019-October/008936.html

It would be great to get some outside feedback on the new PROJ Java bindings! Just be aware that the bindings are still in a development phase and can't be expected to be stable just yet.

**Comment by rouault** [comment]
Closing that issue
