### ISSUE TITLE
asan errors on master build

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/PROJ#1901]
This is quite probably a false positive, but on master builds under libasan I get many errors like this:

```
==633215==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x61100115c140 in thread T20 (Thread (pooled)):
  object passed to delete has wrong type:
  size of the allocated type:   208 bytes;
  size of the deallocated type: 168 bytes.
    #0 0x7f9fd10930b5 in operator delete(void*, unsigned long) (/usr/lib64/libasan.so.5+0x1110b5)
    #1 0x7f9fc200d3b7 in osgeo::proj::SQLite3VFS::~SQLite3VFS() /home/nyall/dev/proj.4/src/sqlite3_utils.cpp:54
    #2 0x7f9fc1f1c691 in std::default_delete<osgeo::proj::SQLite3VFS>::operator()(osgeo::proj::SQLite3VFS*) const /usr/include/c++/9/bits/unique_ptr.h:81
    #3 0x7f9fc1f18747 in std::unique_ptr<osgeo::proj::SQLite3VFS, std::default_delete<osgeo::proj::SQLite3VFS> >::~unique_ptr() /usr/include/c++/9/bits/unique_ptr.h:284
    #4 0x7f9fc1eed7bf in osgeo::proj::io::DatabaseContext::Private::~Private() iso19111/factory.cpp:296
    #5 0x7f9fc1f1d99b in std::default_delete<osgeo::proj::io::DatabaseContext::Private>::operator()(osgeo::proj::io::DatabaseContext::Private*) const /usr/include/c++/9/bits/unique_ptr.h:81
    #6 0x7f9fc1f19a77 in std::unique_ptr<osgeo::proj::io::DatabaseContext::Private, std::default_delete<osgeo::proj::io::DatabaseContext::Private> >::~unique_ptr() /usr/include/c++/9/bits/unique_ptr.h:284
    #7 0x7f9fc1ef07b1 in osgeo::proj::io::DatabaseContext::~DatabaseContext() ../include/proj/io.hpp:802
    #8 0x7f9fc1f30a2f in std::_Sp_counted_ptr<osgeo::proj::io::DatabaseContext*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/9/bits/shared_ptr_base.h:377
    #9 0x7f9fcf44be58 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/9/bits/shared_ptr_base.h:155
    #10 0x7f9fcf4481a9 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/9/bits/shared_ptr_base.h:730
    #11 0x7f9fc1daf0df in std::__shared_ptr<osgeo::proj::io::DatabaseContext, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/9/bits/shared_ptr_base.h:1169
    #12 0x7f9fc1daf0fb in std::shared_ptr<osgeo::proj::io::DatabaseContext>::~shared_ptr() /usr/include/c++/9/bits/shared_ptr.h:103
    #13 0x7f9fc1f53d4d in projCppContext::~projCppContext() ../include/proj/internal/io_internal.hpp:169
    #14 0x7f9fc1f30c96 in proj_context_delete_cpp_context(projCppContext*) iso19111/c_api.cpp:106
    #15 0x7f9fc1fad806 in projCtx_t::~projCtx_t() /home/nyall/dev/proj.4/src/ctx.cpp:166
    #16 0x7f9fc1fad8ef in internal_pj_ctx_free /home/nyall/dev/proj.4/src/ctx.cpp:186
    #17 0x7f9fc1fbf704 in internal_proj_context_destroy /home/nyall/dev/proj.4/src/4D_api.cpp:1397
    #18 0x7f9fc1730945 in OSRPJContextHolder::deinit() /home/nyall/dev/gdal/gdal/ogr/ogr_proj_p.cpp:100
    #19 0x7f9fc1730958 in OSRPJContextHolder::~OSRPJContextHolder() /home/nyall/dev/gdal/gdal/ogr/ogr_proj_p.cpp:92
    #20 0x7f9fbf41474e in __call_tls_dtors (/lib64/libc.so.6+0x3f74e)
    #21 0x7f9fcb3bf4ef in start_thread (/lib64/libpthread.so.0+0x94ef)
    #22 0x7f9fbf4d66d2 in clone (/lib64/libc.so.6+0x1016d2)

0x61100115c140 is located 0 bytes inside of 208-byte region [0x61100115c140,0x61100115c210)
allocated by thread T20 (Thread (pooled)) here:
    #0 0x7f9fd10919d7 in operator new(unsigned long) (/usr/lib64/libasan.so.5+0x10f9d7)
    #1 0x7f9fc200d6c6 in osgeo::proj::SQLite3VFS::create(bool, bool, bool) /home/nyall/dev/proj.4/src/sqlite3_utils.cpp:151
    #2 0x7f9fc1eee4d4 in osgeo::proj::io::DatabaseContext::Private::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, projCtx_t*) iso19111/factory.cpp:515
    #3 0x7f9fc1ef0820 in osgeo::proj::io::DatabaseContext::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, projCtx_t*) iso19111/factory.cpp:841
    #4 0x7f9fc1f30fb4 in projCppContext::getDatabaseContext() iso19111/c_api.cpp:145
    #5 0x7f9fc1f3108e in getDBcontext iso19111/c_api.cpp:156
    #6 0x7f9fc1f32c61 in internal_proj_create_from_database iso19111/c_api.cpp:631
    #7 0x7f9fc16eb4e7 in OGRSpatialReference::importFromEPSGA(int) /home/nyall/dev/gdal/gdal/ogr/ogrspatialreference.cpp:10369

Thread T20 (Thread (pooled)) created by T0 here:
    #0 0x7f9fd0fbc955 in pthread_create (/usr/lib64/libasan.so.5+0x3a955)
    #1 0x7f9fcb49891e in QThread::start(QThread::Priority) (/lib64/libQt5Core.so.5+0xc091e)

SUMMARY: AddressSanitizer: new-delete-type-mismatch (/usr/lib64/libasan.so.5+0x1110b5) in operator delete(void*, unsigned long)
```

**Comment by nyalldawson** [comment]
Ah - sorry for the noise, just worked out the issue

**Comment by nyalldawson** [comment]
Hmm, no - still seeing these...
