### ISSUE TITLE
Null pointer dereference in reverse_obs()

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#566]
This is actually https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3324

Simply way to reproduce
```
$ echo "0 0" | cs2cs +proj=merc +datum=WGS84 +to +proj=ob_tran +o_proj=pipeline +proj=pipeline +o_lat_p +inv +step +proj=unitconvert +t_out=decimalyear +datum=WGS84
```

Crashes in
```
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00000000004223d7 in reverse_obs (obs=..., P=0x67fc40) at PJ_unitconvert.c:317
#2  0x0000000000423f79 in pj_invobs (obs=..., P=0x67fc40) at pj_internal.c:88
#3  0x000000000041a8c8 in proj_trans_obs (P=0x67fc40, direction=PJ_INV, obs=...) at pj_obs_api.c:136
#4  0x000000000041cade in pipeline_forward_obs (point=..., P=0x67ddf0) at PJ_pipeline.c:194
#5  0x000000000041d278 in pipeline_forward (lp=..., P=0x67ddf0) at PJ_pipeline.c:252
#6  0x0000000000446b01 in t_forward (lp=..., P=0x67d960) at PJ_ob_tran.c:45
#7  0x000000000045e5d3 in pj_fwd (lp=..., P=0x67d960) at pj_fwd.c:41
#8  0x000000000040babe in pj_transform (srcdefn=0x67d360, dstdefn=0x67d960, point_count=1, point_offset=1, x=0x7fffffffda70, y=0x7fffffffda78, z=0x0) at pj_transform.c:402
```

time_units[Q->t_in_id].t_out is NULL there. A null check could be added there, but wasn't sure if this is the best fix. Presumably @kbevers will better know

**Comment by kbevers** [comment]
The code in question:
```
    if (Q->t_in_id >= 0)
        out.coo.xyzt.t = time_units[Q->t_out_id].t_in( obs.coo.xyzt.t );
    if (Q->t_out_id >= 0)
        out.coo.xyzt.t = time_units[Q->t_in_id].t_out( out.coo.xyzt.t );
```

The problem seems to be that the two if-statements checks the wrong index. The first one checks that `Q->t_in_id >= 0` but uses `Q->t_out_id` to index the `time_units` array. When I wrote the code I always tested with both input and output time units set. In that case the code works fine since both indices are zero or greater.

The correct code should be:

```
    if (Q->t_out_id >= 0)
        out.coo.xyzt.t = time_units[Q->t_out_id].t_in( obs.coo.xyzt.t );
    if (Q->t_in_id >= 0)
        out.coo.xyzt.t = time_units[Q->t_in_id].t_out( out.coo.xyzt.t );
```

Patch in https://github.com/OSGeo/proj.4/pull/567
